import { builder } from './builder.js'
import './GQLCommon/GQLConcurrentChangeError.js'
import './GQLCommon/GQLPlanAndUserResult.js'
import './GQLCommon/GQLSuccess.js'
import './GQLCommon/GQLUserSuccessResult.js'
import './GQLLinkBasedPlan/GQLCreateLinkBasedPlan.js'
import './GQLLinkBasedPlan/GQLLinkBasedPlan.js'
import './GQLMisc/GQLGeneratePDFReport.js'
import './GQLUser/GQLUserPlan/GQLUserMergeFromClient.js'
import './GQLUser/GQLUserPlan/Mutations/GQLUserPlanCopy.js'
import './GQLUser/GQLUserPlan/Mutations/GQLUserPlanReset.js'
import './GQLUser/GQLUserPlan/Mutations/GQLUserPlanCreate.js'
import './GQLUser/GQLUserPlan/Mutations/GQLUserPlanDelete.js'
import './GQLUser/GQLUserPlan/Mutations/GQLUserPlanSync.js'
import './GQLUser/GQLUserPlan/Mutations/GQLUserPlanUpdate.js'
import './GQLUser/GQLUserPlan/Mutations/GQLUserPlanSetAsMain.js'
import './GQLUser/GQLUserPlan/GQLUserPlan.js'
import './GQLUser/Mutations/GQLSendSignInEmail.js'
import './GQLUser/Mutations/GQLUserSetNonPlanParams.js'
import './GQLUser/GQLUserPlan/Mutations/GQLUserPlanSetAsMain.js'
import './GQLUser/GQLUser.js'

export const schema = builder.toSchema()
