[package]
name = "simulator"
version = "2.10.0"
authors = ["Jacob Mathew <jacobgmathew@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = {version = "0.2.63", features = ["serde-serialize"]}
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
lazy_static = "1.4.0"
js-sys = "0.3.57"
serde = { version = "1.0", features = ["derive"] }

[dependencies.web-sys]
version = "0.3.57"
features = [
  'console',
]

[profile.release]
opt-level = 3
