[package]
name = "simulator"
version = "4.0.0"
authors = ["Jacob Mathew <jacobgmathew@gmail.com>"]
edition = "2018"

[lib]
path="src/lib/lib.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
wasm-bindgen = {version = "0.2.63", features = ["serde-serialize"]}
rand = "0.8.5"
getrandom = { version = "0.2", features = ["js"] }
lazy_static = "1.4.0"
js-sys = "0.3.57"
serde = { version = "1.0", features = ["derive"] }
rand_chacha = "0.3.1"
rayon = "1.8.1"
clap = { version = "4.4.18", features = ["derive"] }
serde_json = "1.0.111"
rstest = "0.18.2"
csv = "1.3.0"
linreg = "0.2.0"
tsify = "0.4.5"

[dependencies.web-sys]
version = "0.3.57"
features = [
  'console',
]

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "my_benchmark"
harness = false

[profile.release]
opt-level = 3
