[package]
name = "simulator"
version = "2.4.0"
authors = ["Jacob Mathew <jacobgmathew@gmail.com>"]
edition = "2018"

# Break out the lib so we can import into benches and bin.
[lib]
path="src/lib/lib.rs"
crate-type = ["lib"]

[[bin]]
name = "simulator"
path = "src/main.rs"

[dependencies]
sentry = "0.34.0"
rand = "0.8.5"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
rand_chacha = "0.3.1"
rayon = "1.8.1"
clap = { version = "4.4.18", features = ["derive"] }
serde_json = "1.0.111"
rstest = "0.18.2"
csv = "1.3.0"
linreg = "0.2.0"
axum = "0.7.5"
tokio = { version = "1.36.0", features = ["full"] }
prost = "0.13.1"
google-cloud-storage = "0.20.0"
dotenv = "0.15.0"
reqwest = "0.12.5"
chrono = "0.4.38"
chrono-tz = "0.9.0"
itertools = "0.13.0"
futures = "0.3.30"
once_cell = "1.19.0"
tower-http = {version = "0.5.2", features = ["trace", "compression-br", "compression-gzip", "compression-deflate", "compression-zstd", "decompression-br", "decompression-gzip", "decompression-deflate", "decompression-zstd", "cors" ]}
http = "1.1.0"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
base64 = "0.22.1"
sentry-tower = { version = "0.34.0", features = ["http"] }



[dependencies.web-sys]
version = "0.3.57"
features = [
  'console',
]

[dev-dependencies]
criterion = "0.5.1"

[build-dependencies]
cc = "1.0"
prost-build = "0.13.1"

[[bench]]
name = "bench_main"
harness = false

[profile.release]
opt-level = 3
# For sentry. (maybe need more? https://github.com/getsentry/sentry-docs/issues/9625)
debug = true 
